### ISSUE TITLE
AsonSerializer: recursive getDeclaredFields returns empty List when class doesn't have any Fields, even if superclasses have

### ISSUE THREAD

**Issue by Maxr1998** [afollestad/ason#19]
[Respective line](https://github.com/afollestad/ason/blob/master/src/main/java/com/afollestad/ason/AsonSerializer.java#L43).

A workaround is to add a dummy field (optionally even with `@AsonIgnore`) to the Class.

**Comment by afollestad** [comment]
Fixed in 1.4.15

**Comment by Maxr1998** [comment]
Thanks for the quick fix! :)
