### ISSUE TITLE
Deserialize json request of Volley into object

### ISSUE THREAD

**Issue by AkshayChordiya** [afollestad/ason#5]
Can we make a custom `JsonObjectRequest` to de-serialize the json and deserialize it using ASON into it's POJO?

I'm not sure if this is the right place to ask this. But looking at #3 I thought we could do something similar for Volley. Maybe I can do it once anyone can guide me about best way to do it.

**Comment by afollestad** [comment]
I have no idea, others are welcome to research it if they'd like.

**Comment by afollestad** [comment]
It actually looks like it's pretty easy to do with a simple subclass: https://developer.android.com/training/volley/request-custom.html

I don't plan on including this in Ason though.

**Comment by AkshayChordiya** [comment]
@afollestad Thanks for the suggestion.
