### ISSUE TITLE
How to correctly deserialize Arrays / Lists with Strings?

### ISSUE THREAD

**Issue by jlelse** [afollestad/ason#9]
When I try to deserialize an Object with an Array<String> (Kotlin) it gives me an error, saying String isn't an array type. Using a List<String> doesn't work either, the list is just empty. How to do it correctly?

**Comment by afollestad** [comment]
@jlelse well if you're serializing primitive/string arrays:

```java
int[] ids = new int[] { 1, 2, 3, 4 };
AsonArray<Integer> array = Ason.serializeArray(ids);
```

And you can of course go back the other direction with deserialization.

**Comment by afollestad** [comment]
@jlelse primitive deserialization of arrays looks like this:

```java
AsonArray<Integer> array = new AsonArray<Integer>()
                .add(1, 2, 3, 4);
int[] primitive = Ason.deserialize(array, int[].class);
```

**Comment by afollestad** [comment]
(as shown in the README 😉 )

It's possible there are compatibility issues with Kotlin if the above don't work.

**Comment by jlelse** [comment]
Yes ok, then I have to do this in Java I think
